### PR TITLE
Fix #66 get_last return the last element available

### LINKED ISSUE #66: Regression in latest activity for commits and events
* Use this setting in gm_pr/settings_projects.py: ```LAST_ACTIVITY_FILTER = ("comments", "events", "commits") #slower but provides more information```
* Submit a PR
* Add a label
 - The latest activity appears as "labeled": ok
* Add a comment
 - The latest activity appears as "commented": ok
* Add another label
 - The latest activity still appears as "commented": not ok
* Add or remove labels and submit new commits: the latest activity still always appears as "commented".
Expected behavior: the latest activity should say "labeled" or "unlabeled" or "committed", depending on the latest action.

For info, this worked in this commit:
```
commit b61cf9a9ea36322a4d6148b78cf9acc220ddf45f
Merge: 875aec3 886c983
Author: Cédric Cabessa <ced@ryick.net>
Date:   Mon Sep 21 20:31:16 2015 +0200

    Merge pull request #60 from Genymobile/cssold
    
    bring back "old pr" css
```

### PR DESCRIPTION
**Pull request by CedricCabessa**

### CODE REVIEW

**Comment by CedricCabessa** [comment]
@caarmen  can you check that?
I don't know how this could worked before ....

**Comment by calvarez-ov** [comment]
It still doesn't work :(
* New PR created: I see "committed": ok
* Label added: I see "labeled": ok
* Comment added: I see "commented": ok
* Label removed: I see "commented": Not ok.  I should see "unlabeled".

**Comment by calvarez-ov** [comment]
wait...

**Comment by calvarez-ov** [comment]
Seems to work now, thanks :)
LGTM

**Comment by amasciulli** [comment]
LGTM (won't troll on the Python -1 index)

**Pull request merged**
