### PR TITLE
add favicon + logo

### PR DESCRIPTION
**Pull request by CedricCabessa**
snap1
snap2

### CODE REVIEW

**Comment by rchutaux** [comment]
LGTM

**Comment by CedricCabessa** [comment]
code update + screenshot

**Comment by amasciulli** [comment]
I'm not seeing the exact same png in the diff and on the screenshot

**Comment by CedricCabessa** [comment]
wow! don't know what happen! did I forgot to click save?
ok, updated now
thank for noticing @amasciulli

**Comment by amasciulli** [comment]
Cool :+1: also, I think the logo show say "pull requests" plural, but that can be done later. I would gladly ping christophe but he doesn't seem to have a github account, what a shame. Anyway, LGTM

**Pull request merged**
