### PR TITLE
Minor bugfixes

### LINKED ISSUE #58: "Back to project list" doesn't direct to project list
On the project page, clicking on "Back to project list" redirects to http://jenkins.genymobile.com instead of http://jenkins.genymobile.com/gm_pr

### LINKED ISSUE #59: Footer overlaps bottom of screen
The floating footer overlaps the bottom for the screen, hiding some PRs.

screen shot 2015-08-29 at 15 54 03

### PR DESCRIPTION
**Pull request by amasciulli**
* Remove footer from project list since it's a bit useless and it overlaps the last PRs (fixes #59)
 * Fix "Back to projects" link (redirects to . instead of /) (fixes #58)

### CODE REVIEW

**Comment by CedricCabessa** [comment]
heu... It's not really a fix for #59 ;-)
Can we find a proper solution with some css magic to keep the footer? It's not that I absolutely want a footer but I feel bad about removing it just because we can't fix it properly.

Well done for #58

**Comment by amasciulli** [comment]
I admit I tried to fix it and gave up because I don't like doing CSS, but in the end I honestly think it's better without the footer

**Comment by CedricCabessa** [comment]
Ok, I give up.
I can't do something clean with css (fuck css and the web)
Anyway you're probably right, the footer on the home page is enough.

LGTM

**Comment by jcleneveu-geny** [comment]
LGTM

**Pull request merged**
